---
title: "Neuronal Differentiation"
author: "Stumpf PS"
date: "7 October 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, error=FALSE, warning=FALSE, auto.dep=TRUE,
                      echo=TRUE, tidy=TRUE, width.cutoff=50, fig.width = 4, fig.asp = 1)
options(digits=2)
suppressPackageStartupMessages({
  # for microarrays
    library(lumi)
    library(lumiMouseIDMapping)
  # for colour
    library(marray)
    library(RColorBrewer)
    library(dendroextras)
  # heatmap
    library(gplots)
  # reorder dendrogram
    library(dendextend) })
```

```{r LoadAndNormalise, cache.lazy=FALSE}
source("./R/SingleCell-Load+Normalise.R")
```

# Single Cell Arrays

## Heatmap and hierarchical clustering

```{r sc-Heatmap_SetUp, eval=FALSE}
# calculate dendrogram for genes
dend.genes <- as.dendrogram(hclust(dist(timecourse.log2, method="euclidean"), method="complete"))
# pre-reorder
dend.genes <- reorder(dend.genes, apply(timecourse.log2,1,median))
# manually swap leafes to place Actb next to Gapdh
# dend.genes <- dendextend::click_rotate(dend.genes, continue=T,las=2)

# calculate dendrogram for samples
# simplified sample names for reordering
tc.log2 <- timecourse.log2
colnames(tc.log2) <- sample.factor
# calculate dendrogram
dend.samples <- as.dendrogram(hclust(dist(t(tc.log2), method="euclidean"),method="complete"))
# calculate dendrogram again with coloured clusters
dend.samples <- dendroextras::colour_clusters(hclust(dist(t(tc.log2), method="euclidean"),
                method="complete"), dim(tc.log2)[2],
                col=as.vector(sample.colours)[order.dendrogram(dend.samples)])
# reorder to match sample groups
dend.samples <- reorder(dend.samples, timecourse.log2[c(67,96),], agglo.FUN=sum, node.par)
par(cex=.6)
# dend.samp 	 <- click_rotate(dend.samples, continue=T, las=2)
par(cex=1)
# cleanup
rm(tc.log2)
```

```{r sc-Heatmap_Plot, fig.width=6.6, fig.asp=.6}
load('./data/scHeatmap-ordering.RData')
# Heatmap of entire dataset
heatmap.2(as.matrix(timecourse.log2),
          dendrogram="both", Rowv=dend.genes, Colv=dend.samp,
					ColSideColors=as.vector(factor(line.factor, labels=col.line)),
					RowSideColors=as.vector(gene.info[,3]),
					trace="none", margins = c(.5, .5),
					key=T, keysize=1, density.info="none", key.title=NA, key.xlab=NA,
					key.par=list(mgp=c(.5,0.5,0),
								 mar=c(2,.5,2,.5)+.1),
					key.xtickfun=function() {
               cex  <- par("cex")*par("cex.axis")
               side <- 1
               line <- 0
               col  <- par("col.axis")
               font <- par("font.axis")
               mtext("low", side=side, at=0, adj=0,
                     line=line, cex=cex, col=col, font=font)
               mtext("high", side=side, at=1, adj=1,
                     line=line, cex=cex, col=col, font=font)
               mtext("Expression Threshold", side=3, font=3, col=col, cex=.45)      
               return(list(labels=FALSE, tick=FALSE))},
					labCol=F, labRow=F, col=heatmap.col, sepcolor=NA,
					lwid=c(1, 6), lhei=c(1,3))
```

```{r sc-Heatmap_Legend, fig.width=6.6, fig.asp=.3, echo=FALSE}
par(mar=c(0,0,0,0))

plot.new()					

legend('top',    ncol=7, legend=levels(as.factor(sample.factor)),
       fill=col.time, border=F, bty="n", xpd=NA, title="time [h]", cex=.75)

legend('center', ncol=2, legend=c("E14tg2a", "R1"), fill=col.line,
       border=F, bty="n", xpd=NA, title="Cell line", cex=.75)

legend('bottom', ncol=4, legend=levels(as.factor(gene.info[,1])), fill=levels(gene.info[,3]),
       border=F, bty="n", xpd=NA, title="Category", cex=.75)
```

## Expression distribution

```{r}
# boxplot or beanplots for individual genes
goi <- c('Actb', 'Esrrb', 'Fgf5', 'Nestin', 'Pou5f1')
gix <- which(rownames(timecourse.log2) %in% goi)
  
par(ask=F, bty="n", xpd=NA)
for (i in gix) {
  try(beanplot::beanplot(timecourse.log2[i,] ~ line.factor + sample.factor,
				 side="b", cutmin=0, cutmax=28, what=c( F, T, F, F ), innerborder=NA, border=NA,
				 col=list(c("midnightblue", "black", "black", "midnightblue"), c("darkmagenta", "black", "black", "darkmagenta")),
				 beanlines="median", ylim=c(0,21), log="", ll = 0.1, main=rownames(timecourse.log2)[i], bw=1.5,
				 at=0:6, xlim=c(-.5,6.5), las=1, xlab="hours",
				 ylab="Expression Threshold"), T)
  legend('topright', legend = c('E14', 'R1'), text.col = c('midnightblue','darkmagenta'), bty = 'n', ncol = 1)
}

```

## Principal component analysis & k-means

```{r sc-PCA}
par(mar=c(1,1,2,1), pty="s")
celllines <- list(E14=E14, R1=R1)
clusters <- list()

for (line in c('E14','R1')) {

  # Principal Component Analysis on binary expr data (ET > 2)
pca.tc <- princomp(t(timecourse.log2[,celllines[[line]]]>2))

# Extract scores
xs <- pca.tc$scores[,1]
ys <- pca.tc$scores[,2]
xsign <- -sign(xs[1])
ysign <- -sign(ys[1])

# flip axis to have 0h in bottom left corner (uses first cell as reference)
xs <-  xsign* xs
ys <-  ysign* ys

# Percent variance explained:
varexpl <- (pca.tc$sdev^2/sum(pca.tc$sdev^2))[1:10]

# Plot Scores
plot(x=xs, y=ys, las=1, bty='n', main=line, xlab='', ylab='',
     col=as.vector(sample.colours[celllines[[line]]]), pch=19, cex=1.5, axes=F)
  mtext(paste0("PC1 (", signif(varexpl[1]*100,3),"%)"), side=1)
  mtext(paste0("PC2 (", signif(varexpl[2]*100,3),"%)"), side=2)
lines(tapply(xs, sample.factor[celllines[[line]]], mean), 
      tapply(ys, sample.factor[celllines[[line]]], mean), col='#555555', lwd=4)

# Color by kmeans
clu <- kmeans(cbind(xs,ys), centers = 3, nstart = 10)$cluster
clu <- factor(clu, levels=order(tapply(xs, INDEX = clu, FUN = mean)), labels=1:3)
clusters[[line]] <- as.numeric(as.vector(clu))

plot(x=xs, y=ys, las=1, bty='n', main=line,
     col=clusters[[line]]+5, pch=19, cex=1.5, axes=F)
  mtext(paste0("PC1 (", signif(varexpl[1]*100,3),"%)"), side=1)
  mtext(paste0("PC2 (", signif(varexpl[2]*100,3),"%)"), side=2)
}
```





